package Windows;


import Game.Game;
import java.awt.CardLayout;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**

 @author schmidmichae
 */
public class MainMenu extends javax.swing.JFrame
{

   /**
    Creates new form MainMenu
    */
   public MainMenu()
   {
      initComponents();
      CardLayout cl = (CardLayout)getContentPane().getLayout();
      cl.show(getContentPane(), "menu");
      difficulty = 1;
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      gamePanel = new javax.swing.JPanel();
      menuPanel = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      singlePlayerButton = new javax.swing.JButton();
      twoPlayerButton = new javax.swing.JButton();
      settingsButton = new javax.swing.JButton();
      creditsButton = new javax.swing.JButton();
      informationButton = new javax.swing.JButton();
      settingsPanel = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      singlePlayerButton1 = new javax.swing.JButton();
      difficultyLabel = new javax.swing.JLabel();
      singlePlayerButton2 = new javax.swing.JButton();
      singlePlayerButton3 = new javax.swing.JButton();
      singlePlayerButton4 = new javax.swing.JButton();
      singlePlayerButton5 = new javax.swing.JButton();
      singlePlayerButton7 = new javax.swing.JButton();
      creditsPanel = new javax.swing.JPanel();
      jPanel4 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      difficultyLabel1 = new javax.swing.JLabel();
      singlePlayerButton14 = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      infoPanel = new javax.swing.JPanel();
      jPanel5 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      difficultyLabel2 = new javax.swing.JLabel();
      singlePlayerButton15 = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));
      setMinimumSize(new java.awt.Dimension(800, 600));
      getContentPane().setLayout(new java.awt.CardLayout());

      gamePanel.setMinimumSize(new java.awt.Dimension(800, 600));
      gamePanel.setPreferredSize(new java.awt.Dimension(800, 600));

      javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
      gamePanel.setLayout(gamePanelLayout);
      gamePanelLayout.setHorizontalGroup(
         gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      gamePanelLayout.setVerticalGroup(
         gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      getContentPane().add(gamePanel, "game");

      menuPanel.setBackground(new java.awt.Color(0, 0, 0));
      menuPanel.setMinimumSize(new java.awt.Dimension(800, 600));
      menuPanel.setName(""); // NOI18N
      menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
      menuPanel.setRequestFocusEnabled(false);

      jPanel2.setBackground(new java.awt.Color(255, 255, 255));

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Wall Ball");
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      singlePlayerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton.setText("One Player");
      singlePlayerButton.setBorderPainted(false);
      singlePlayerButton.setContentAreaFilled(false);
      singlePlayerButton.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButtonActionPerformed(evt);
         }
      });

      twoPlayerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      twoPlayerButton.setText("Two Player");
      twoPlayerButton.setBorderPainted(false);
      twoPlayerButton.setContentAreaFilled(false);
      twoPlayerButton.setMaximumSize(new java.awt.Dimension(90, 23));
      twoPlayerButton.setMinimumSize(new java.awt.Dimension(90, 23));
      twoPlayerButton.setPreferredSize(new java.awt.Dimension(90, 23));
      twoPlayerButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            twoPlayerButtonActionPerformed(evt);
         }
      });

      settingsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      settingsButton.setText("Settings");
      settingsButton.setBorderPainted(false);
      settingsButton.setContentAreaFilled(false);
      settingsButton.setMaximumSize(new java.awt.Dimension(90, 23));
      settingsButton.setMinimumSize(new java.awt.Dimension(90, 23));
      settingsButton.setPreferredSize(new java.awt.Dimension(90, 23));
      settingsButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            settingsButtonActionPerformed(evt);
         }
      });

      creditsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      creditsButton.setText("Credits");
      creditsButton.setBorderPainted(false);
      creditsButton.setContentAreaFilled(false);
      creditsButton.setMaximumSize(new java.awt.Dimension(90, 23));
      creditsButton.setMinimumSize(new java.awt.Dimension(90, 23));
      creditsButton.setPreferredSize(new java.awt.Dimension(90, 23));
      creditsButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            creditsButtonActionPerformed(evt);
         }
      });

      informationButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      informationButton.setText("Information");
      informationButton.setBorderPainted(false);
      informationButton.setContentAreaFilled(false);
      informationButton.setMaximumSize(new java.awt.Dimension(90, 23));
      informationButton.setMinimumSize(new java.awt.Dimension(90, 23));
      informationButton.setPreferredSize(new java.awt.Dimension(90, 23));
      informationButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            informationButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(singlePlayerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(twoPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                     .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                     .addComponent(creditsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                     .addComponent(informationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
                  .addContainerGap())))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(singlePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(twoPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(creditsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(informationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(165, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
      menuPanel.setLayout(menuPanelLayout);
      menuPanelLayout.setHorizontalGroup(
         menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(menuPanelLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(31, 31, 31))
      );
      menuPanelLayout.setVerticalGroup(
         menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(menuPanelLayout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(80, 80, 80))
      );

      getContentPane().add(menuPanel, "menu");

      settingsPanel.setBackground(new java.awt.Color(0, 0, 0));
      settingsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
      settingsPanel.setName(""); // NOI18N
      settingsPanel.setRequestFocusEnabled(false);

      jPanel3.setBackground(new java.awt.Color(255, 255, 255));

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel2.setText("Wall Ball Settings");
      jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      singlePlayerButton1.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton1.setForeground(new java.awt.Color(0, 153, 0));
      singlePlayerButton1.setText("Easy");
      singlePlayerButton1.setContentAreaFilled(false);
      singlePlayerButton1.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton1.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton1.setOpaque(true);
      singlePlayerButton1.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton1ActionPerformed(evt);
         }
      });

      difficultyLabel.setBackground(new java.awt.Color(0, 153, 153));
      difficultyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      difficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      difficultyLabel.setText("Difficulty: Medium");
      difficultyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      difficultyLabel.setOpaque(true);

      singlePlayerButton2.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton2.setForeground(new java.awt.Color(0, 153, 0));
      singlePlayerButton2.setText("Medium");
      singlePlayerButton2.setContentAreaFilled(false);
      singlePlayerButton2.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton2.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton2.setOpaque(true);
      singlePlayerButton2.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton2ActionPerformed(evt);
         }
      });

      singlePlayerButton3.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton3.setForeground(new java.awt.Color(204, 102, 0));
      singlePlayerButton3.setText("Hard");
      singlePlayerButton3.setContentAreaFilled(false);
      singlePlayerButton3.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton3.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton3.setOpaque(true);
      singlePlayerButton3.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton3ActionPerformed(evt);
         }
      });

      singlePlayerButton4.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton4.setForeground(new java.awt.Color(204, 102, 0));
      singlePlayerButton4.setText("Very Hard");
      singlePlayerButton4.setContentAreaFilled(false);
      singlePlayerButton4.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton4.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton4.setOpaque(true);
      singlePlayerButton4.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton4ActionPerformed(evt);
         }
      });

      singlePlayerButton5.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      singlePlayerButton5.setForeground(new java.awt.Color(204, 0, 0));
      singlePlayerButton5.setText("Insane");
      singlePlayerButton5.setContentAreaFilled(false);
      singlePlayerButton5.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton5.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton5.setOpaque(true);
      singlePlayerButton5.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton5.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton5ActionPerformed(evt);
         }
      });

      singlePlayerButton7.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      singlePlayerButton7.setText("<-  Return To Main Menu");
      singlePlayerButton7.setContentAreaFilled(false);
      singlePlayerButton7.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton7.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton7.setOpaque(true);
      singlePlayerButton7.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton7.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton7ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(singlePlayerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(difficultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
               .addComponent(singlePlayerButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(singlePlayerButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(singlePlayerButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(singlePlayerButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(singlePlayerButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(difficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(singlePlayerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(singlePlayerButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(singlePlayerButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(singlePlayerButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(singlePlayerButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(68, 68, 68)
            .addComponent(singlePlayerButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addGap(23, 23, 23))
      );

      javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
      settingsPanel.setLayout(settingsPanelLayout);
      settingsPanelLayout.setHorizontalGroup(
         settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(settingsPanelLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(31, 31, 31))
      );
      settingsPanelLayout.setVerticalGroup(
         settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(settingsPanelLayout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(80, 80, 80))
      );

      getContentPane().add(settingsPanel, "settings");

      creditsPanel.setBackground(new java.awt.Color(0, 0, 0));
      creditsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
      creditsPanel.setName(""); // NOI18N
      creditsPanel.setRequestFocusEnabled(false);

      jPanel4.setBackground(new java.awt.Color(255, 255, 255));

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel3.setText("Wall Ball Credits");
      jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      difficultyLabel1.setBackground(new java.awt.Color(0, 153, 153));
      difficultyLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      difficultyLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      difficultyLabel1.setText("Credits");
      difficultyLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      difficultyLabel1.setOpaque(true);

      singlePlayerButton14.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      singlePlayerButton14.setText("<-  Return To Main Menu");
      singlePlayerButton14.setContentAreaFilled(false);
      singlePlayerButton14.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton14.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton14.setOpaque(true);
      singlePlayerButton14.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton14.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton14ActionPerformed(evt);
         }
      });

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel4.setText("<html>\nContributors:<br>\nBrady Dow<br>\nMichael Schmidt<br>\nEdgar Mcbee<br>\nJames Eten<br>\nBen Schnel\n</html>");
      jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(difficultyLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
               .addComponent(singlePlayerButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                  .addComponent(jLabel4)
                  .addContainerGap())))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(difficultyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(singlePlayerButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(16, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
      creditsPanel.setLayout(creditsPanelLayout);
      creditsPanelLayout.setHorizontalGroup(
         creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(creditsPanelLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(31, 31, 31))
      );
      creditsPanelLayout.setVerticalGroup(
         creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(creditsPanelLayout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(80, 80, 80))
      );

      getContentPane().add(creditsPanel, "credits");

      infoPanel.setBackground(new java.awt.Color(0, 0, 0));
      infoPanel.setMinimumSize(new java.awt.Dimension(800, 600));
      infoPanel.setName(""); // NOI18N
      infoPanel.setRequestFocusEnabled(false);

      jPanel5.setBackground(new java.awt.Color(255, 255, 255));

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel5.setText("Wall Ball Information");
      jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      difficultyLabel2.setBackground(new java.awt.Color(0, 153, 153));
      difficultyLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      difficultyLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      difficultyLabel2.setText("How To Play:");
      difficultyLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      difficultyLabel2.setOpaque(true);

      singlePlayerButton15.setBackground(new java.awt.Color(204, 204, 204));
      singlePlayerButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      singlePlayerButton15.setText("<-  Return To Main Menu");
      singlePlayerButton15.setContentAreaFilled(false);
      singlePlayerButton15.setMaximumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton15.setMinimumSize(new java.awt.Dimension(90, 23));
      singlePlayerButton15.setOpaque(true);
      singlePlayerButton15.setPreferredSize(new java.awt.Dimension(90, 23));
      singlePlayerButton15.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            singlePlayerButton15ActionPerformed(evt);
         }
      });

      jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel6.setText("<html>\nFirst player movement: use \"W\" to go up and \"S\" to go down.<br> \nSecond player movement: use \"Arrow key up\" to go up and \"Arrow key down\" to go down.<br> <br>\nThe game is played like a classic game of pong but you are given a number of lives\nwhich is displayed on each screen side that goes down when the other player scores.<br><br>\nThere are several power ups which modify how the game is played and are picked up when the ball rolls into the powerup field.\n</html>");
      jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(difficultyLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
               .addComponent(singlePlayerButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                  .addContainerGap())))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(difficultyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(singlePlayerButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(16, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
      infoPanel.setLayout(infoPanelLayout);
      infoPanelLayout.setHorizontalGroup(
         infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(infoPanelLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(31, 31, 31))
      );
      infoPanelLayout.setVerticalGroup(
         infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(infoPanelLayout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(80, 80, 80))
      );

      getContentPane().add(infoPanel, "info");

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButtonActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButtonActionPerformed
      //Clear an old game
      if(game != null)
         ((CardLayout)(getContentPane().getLayout())).removeLayoutComponent(game);
      
      game = new Game(Game.SINGLEPLAYER, getContentPane());
      game.setMaximumSize(gamePanel.getMaximumSize());
      game.setMinimumSize(gamePanel.getMinimumSize());
      game.setSize(gamePanel.getSize());
      getContentPane().add(game, "gameWindow");
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "gameWindow");
      game.requestFocusInWindow();
   }//GEN-LAST:event_singlePlayerButtonActionPerformed

   private void twoPlayerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_twoPlayerButtonActionPerformed
   {//GEN-HEADEREND:event_twoPlayerButtonActionPerformed
      //Clear an old game
      if(game != null)
         ((CardLayout)(getContentPane().getLayout())).removeLayoutComponent(game);
      
      game = new Game(Game.TWO_PLAYER, getContentPane());
      game.setMaximumSize(gamePanel.getMaximumSize());
      game.setMinimumSize(gamePanel.getMinimumSize());
      game.setSize(gamePanel.getSize());
      getContentPane().add(game, "gameWindow");
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "gameWindow");
      game.requestFocusInWindow();
   }//GEN-LAST:event_twoPlayerButtonActionPerformed

   private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_settingsButtonActionPerformed
   {//GEN-HEADEREND:event_settingsButtonActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "settings");
   }//GEN-LAST:event_settingsButtonActionPerformed

   private void singlePlayerButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton7ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton7ActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "menu");
   }//GEN-LAST:event_singlePlayerButton7ActionPerformed

   private void singlePlayerButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton1ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton1ActionPerformed
      difficulty = 0;
      difficultyLabel.setText("Difficulty: Easy");
   }//GEN-LAST:event_singlePlayerButton1ActionPerformed

   private void singlePlayerButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton2ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton2ActionPerformed
      difficulty = 1;
      difficultyLabel.setText("Difficulty: Medium");
   }//GEN-LAST:event_singlePlayerButton2ActionPerformed

   private void singlePlayerButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton3ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton3ActionPerformed
      difficulty = 2;
      difficultyLabel.setText("Difficulty: Hard");
   }//GEN-LAST:event_singlePlayerButton3ActionPerformed

   private void singlePlayerButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton4ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton4ActionPerformed
      difficulty = 3;
      difficultyLabel.setText("Difficulty: Very Hard");
   }//GEN-LAST:event_singlePlayerButton4ActionPerformed

   private void singlePlayerButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton5ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton5ActionPerformed
      difficulty = 4;
      difficultyLabel.setText("Difficulty: Insane");
   }//GEN-LAST:event_singlePlayerButton5ActionPerformed

   private void singlePlayerButton14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton14ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton14ActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "menu");
   }//GEN-LAST:event_singlePlayerButton14ActionPerformed

   private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_creditsButtonActionPerformed
   {//GEN-HEADEREND:event_creditsButtonActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "credits");
   }//GEN-LAST:event_creditsButtonActionPerformed

   private void singlePlayerButton15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_singlePlayerButton15ActionPerformed
   {//GEN-HEADEREND:event_singlePlayerButton15ActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "menu");
   }//GEN-LAST:event_singlePlayerButton15ActionPerformed

   private void informationButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_informationButtonActionPerformed
   {//GEN-HEADEREND:event_informationButtonActionPerformed
      ((CardLayout)(getContentPane().getLayout())).show(getContentPane(), "info");
   }//GEN-LAST:event_informationButtonActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new MainMenu().setVisible(true);
         }
      });
   }

   private Game game;
   public static int difficulty = 1;
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton creditsButton;
   private javax.swing.JPanel creditsPanel;
   private javax.swing.JLabel difficultyLabel;
   private javax.swing.JLabel difficultyLabel1;
   private javax.swing.JLabel difficultyLabel2;
   private javax.swing.JPanel gamePanel;
   private javax.swing.JPanel infoPanel;
   private javax.swing.JButton informationButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel menuPanel;
   private javax.swing.JButton settingsButton;
   private javax.swing.JPanel settingsPanel;
   private javax.swing.JButton singlePlayerButton;
   private javax.swing.JButton singlePlayerButton1;
   private javax.swing.JButton singlePlayerButton14;
   private javax.swing.JButton singlePlayerButton15;
   private javax.swing.JButton singlePlayerButton2;
   private javax.swing.JButton singlePlayerButton3;
   private javax.swing.JButton singlePlayerButton4;
   private javax.swing.JButton singlePlayerButton5;
   private javax.swing.JButton singlePlayerButton7;
   private javax.swing.JButton twoPlayerButton;
   // End of variables declaration//GEN-END:variables
}
